[tool.poetry]
name = "unsupervised"
version = "0.1.0"
description = ""
authors = ["Vanessa Lopera <vanesalo104@gamil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
